# Generated by Django 3.2.7 on 2023-03-20 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LiverPool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Selnium', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Ticket List',
            },
        ),
    ]
